export const REDUX_WP_API_CALL = 'REDUX_WP_API_CALL';
export const REDUX_WP_API_REQUEST = 'REDUX_WP_API_REQUEST';
export const REDUX_WP_API_FAILURE = 'REDUX_WP_API_FAILURE';
export const REDUX_WP_API_SUCCESS = 'REDUX_WP_API_SUCCESS';
export const REDUX_WP_API_CACHE_HIT = 'REDUX_WP_API_CACHE_HIT';
export const REDUX_WP_API_PROVIDE = 'REDUX_WP_API_PROVIDE';
